name: Push to main

on:
    push:
        branches:
            - main

permissions:
    contents: read

jobs:
    ci:
        name: CI
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

            - name: Run CI checks
              uses: ./.github/actions/ci
              with:
                  node-auth-token: ${{ secrets.GITHUB_TOKEN }}
