name: Release

on:
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
    contents: read

jobs:
    validate:
        name: Validate release tag
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
              with:
                  fetch-depth: 0

            - name: Validate release tag
              uses: dnd-mapp/action-validate-release-tag@cc07c1784188a50b4d1f931131bb14e480b2dd2a # v1.0.0

            - name: Check changelog section
              uses: dnd-mapp/action-extract-release-notes@2c44a78312de6d557ac11a76c316de06387824ee # v1.0.0
              with:
                  write-file: 'false'
              env:
                  RELEASED_VERSION: ${{ github.ref_name }}

            - name: Run CI checks
              uses: ./.github/actions/ci
              with:
                  node-auth-token: ${{ secrets.GITHUB_TOKEN }}

    release:
        name: Publish release
        needs: validate
        runs-on: ubuntu-22.04
        environment: package-publish
        permissions:
            contents: write
            discussions: write
            packages: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

            - name: Setup workspace
              uses: dnd-mapp/action-setup-workspace@d5d3148fe3fbe34055eb006f685f190524c16522 # v2.0.0
              with:
                  node-auth-token: ${{ secrets.GITHUB_TOKEN }}

            - name: Prepare release notes
              uses: dnd-mapp/action-extract-release-notes@2c44a78312de6d557ac11a76c316de06387824ee # v1.0.0
              env:
                  RELEASED_VERSION: ${{ github.ref_name }}

            - name: Build package
              shell: bash
              run: node scripts/pre-publish-only.mjs

            - name: Pack release tarball
              id: pack
              shell: bash
              working-directory: dist
              run: |
                  pnpm pack --pack-destination ..
                  echo "tarball=$(realpath ../*.tgz)" >> "$GITHUB_OUTPUT"

            - name: Create GitHub release
              uses: dnd-mapp/action-create-github-release@16f4127e1c004e084e70c6874098153a6b85457b # v1.0.0
              with:
                  assets: ${{ steps.pack.outputs.tarball }}

            - name: Publish package
              shell: bash
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  pnpm config set "//npm.pkg.github.com/:_authToken" "$NODE_AUTH_TOKEN"
                  pnpm publish "${{ steps.pack.outputs.tarball }}" --no-git-checks
